# Site settings
title: Shivan Kaul Sahib
email: shivankaulsahib@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My grandmother's life story, transcribed on my trip to Chandigarh 2014.
baseurl: "/Naani" # the subpath of your site, e.g. /blog/
url: "naani.shivankaulsahib.me" # the base hostname & protocol for your site
github_username:  ShivanKaul

# Build settings
markdown: kramdown
